[site]
title = "Axe Pictures"
subtitle = "Single Bits"
description = "by Axe Barbie"
author = "Axe Barbie"
logo = "../images/axebarbie.svg"

[[site.icons]]
icon = "../images/takemymoney.svg"
link = "https://www.ebay.com/usr/axebarbie"
label = "View eBay store"

[[site.nav]]
text = "Single Bits"
link = "../single-bits"
label = "View single bits"

[[site.nav]]
text = "Boy's Axes"
link = "../boys-axes"
label = "View boy's axes"

[[site.nav]]
text = "Hatchets"
link = "../hatchets"
label = "View hatchets"

[[site.nav]]
text = "Double Bits"
link = "../double-bits"
label = "View double bits"

[[site.nav]]
text = "Power Tools"
link = "../power-tools"
label = "View power tools"

[[site.nav]]
text = "Catalogs"
link = "../catalogs"
label = "View catalogs"

[image]
thumbnailWidth = 640
originalWidth = 0

[layout]
minColumn = 3
maxColumn = 4
minWidth = 200

[[section]]
title = "Clark Witbeck Co. Dorpian"
text = "1870 - 3 lb"
slug = "dorpian"
folder = "photos/dorpian"
ascending = true

[[section]]
title = "H.S.B. & Co. Our Very Best"
text = "1920's - 3½ lb"
slug = "ovb"
folder = "photos/ovb"
ascending = true

[[section]]
title = "French Bigoire Damascus"
text = "1890's - 4.5 lb"
slug = "bigoire"
folder = "photos/bigoire"
ascending = true

[[section]]
title = "Hytest Forged Tools"
text = "1940's - 4 lb"
slug = "hytest"
folder = "photos/hytest"
ascending = true

[[section]]
title = "Hartwell Brothers Grey Gorge"
text = "1940's - 3½ lb"
slug = "grey-gorge"
folder = "photos/grey-gorge"
ascending = true

[[section]]
title = "J.P.H. Co. Everkeen"
text = "1890's - 3 lb"
slug = "everkeen"
folder = "photos/everkeen"
ascending = true

[[section]]
title = "Marshall Wells Northern King"
text = "1930's - 3½ lb"
slug = "northern-king"
folder = "photos/northern-king"
ascending = true

[[section]]
title = "Tramontina"
text = "1930's - 3½ lb"
slug = "tramontina"
folder = "photos/tramontina"
ascending = true

[[section]]
title = "Plumb"
text = "1950's - 4½ lb"
slug = "plumb5"
folder = "photos/plumb5"
ascending = true

[[section]]
title = "Council Tool Splitting Axe"
text = "2022 - 5 lb"
slug = "ct-splitting-axe"
folder = "photos/ct-splitting-axe"
ascending = true

[[section]]
title = "Council Tool Velvicut American Felling Axe"
text = "2021 - 4 lb"
slug = "velvicut-dayton"
folder = "photos/velvicut-dayton"
ascending = true

[[section]]
title = "Kelly Axe Mfg. Co."
text = "1904 - 3 lb"
slug = "kelly"
folder = "photos/kelly"
ascending = true

[[section]]
title = "Kelly Works Falls City"
text = "1920's - 3½ lb"
slug = "falls-city"
folder = "photos/falls-city"
ascending = true

[[section]]
title = "Collins Bonded"
text = "1950's - 3½ lb"
slug = "bonded"
folder = "photos/bonded"
ascending = true

[[section]]
title = "Plumb"
text = "1940's - 4 lb"
slug = "plumb4"
folder = "photos/plumb4"
ascending = true

[[section]]
title = "Dunlap"
text = "1930's - 3 lb"
slug = "dunlap"
folder = "photos/dunlap"
ascending = true

[[section]]
title = "Plumb Department of Wildlife"
text = "1930's - 3 lb"
slug = "plumb-dow"
folder = "photos/plumb-dow"
ascending = true

[[section]]
title = "Unknown"
text = "1930's USA - 3½ lb"
slug = "usa"
folder = "photos/usa"
ascending = true

[[section]]
title = "Plumb"
text = "1930's - 3½ lb"
slug = "plumb3"
folder = "photos/plumb3"
ascending = true

[[section]]
title = "Unknown"
text = "1890's - 3 lb"
slug = "unknown-dayton"
folder = "photos/unknown-dayton"
ascending = true

[[section]]
title = "Council Tool North Carolina"
text = "1920's - 4 lb"
slug = "ct-north-carolina"
folder = "photos/ct-north-carolina"
ascending = true

[[section]]
title = "Plumb"
text = "1930's - 3½ lb"
slug = "plumb2"
folder = "photos/plumb2"
ascending = true

[[section]]
title = "Peters Cartridge Co."
text = "1890's - 3 lb"
slug = "peters"
folder = "photos/peters"
ascending = true

[[section]]
title = "Plumb"
text = "1950's - 3½ lb"
slug = "plumb"
folder = "photos/plumb"
ascending = true

[[section]]
title = "Collins Homestead"
text = "1960's - 3 lb"
slug = "homestead"
folder = "photos/homestead"
ascending = true

[[section]]
title = "Plumb Au-To-Graf"
text = "1930's - 3 lb"
slug = "autograf"
folder = "photos/autograf"
ascending = true

[[section]]
title = "Collins Old Timer"
text = "1940's - 3½ lb single bit"
slug = "old-timer"
folder = "photos/old-timer"
ascending = true

[others]
folders = [ "photos" ]
