[site]
title = "Axe Pictures"
subtitle = "Double Bits"
description = "by Axe Barbie"
author = "Axe Barbie"
logo = "../images/axebarbie.svg"

[[site.icons]]
icon = "../images/takemymoney.svg"
link = "https://www.ebay.com/usr/axebarbie"
label = "View eBay store"

[[site.nav]]
text = "Single Bits"
link = "../single-bits"
label = "View single bits"

[[site.nav]]
text = "Boy's Axes"
link = "../boys-axes"
label = "View boy's axes"

[[site.nav]]
text = "Hatchets"
link = "../hatchets"
label = "View hatchets"

[[site.nav]]
text = "Double Bits"
link = "../double-bits"
label = "View double bits"

[[site.nav]]
text = "Power Tools"
link = "../power-tools"
label = "View power tools"

[[site.nav]]
text = "Catalogs"
link = "../catalogs"
label = "View catalogs"

[image]
thumbnailWidth = 640
originalWidth = 0

[layout]
minColumn = 3
maxColumn = 4
minWidth = 200

[[section]]
title = "Marshall Wells Zenith"
text = "1912 - 3½ lb"
slug = "zenith-double-bit"
folder = "photos/zenith-double-bit"
ascending = true

[[section]]
title = "Morley-Murphy Hdwe. Co. Wedgeway"
text = "1920's - 3½ lb"
slug = "wedgeway"
folder = "photos/wedgeway"
ascending = true

[[section]]
title = "Sager Chemical Axe"
text = "1941 - 3½ lb"
slug = "sager-1941"
folder = "photos/sager-1941"
ascending = true

[[section]]
title = "M.W.H. Co. Hand Made"
text = "1890's - 3½ lb"
slug = "hand-made"
folder = "photos/hand-made"
ascending = true

[[section]]
title = "Lakeside"
text = "1920's - 3½ lb"
slug = "lakeside"
folder = "photos/lakeside"
ascending = true

[[section]]
title = "Sager Chemical Axe"
text = "1929 - 3½ lb"
slug = "sager-1928"
folder = "photos/sager-1928"
ascending = true

[[section]]
title = "True Temper Flint Edge"
text = "1950's - 3½ lb"
slug = "flint-edge"
folder = "photos/flint-edge"
ascending = true

[[section]]
title = "Gambles Artisan"
text = "1920's - 3 lb"
slug = "artisan"
folder = "photos/artisan"
ascending = true

[[section]]
title = "C.M. McClung"
text = "1890's - 3½ lb"
slug = "cm-mcclung"
folder = "photos/cm-mcclung"
ascending = true

[[section]]
title = "Warren Axe & Tool Co. Sager"
text = "1950 - 3 lb"
slug = "sager-1950"
folder = "photos/sager-1950"
ascending = true

[[section]]
title = "Unknown"
text = "1930's - 3½ lb"
slug = "unknown-double-bit"
folder = "photos/unknown-double-bit"
ascending = true

[[section]]
title = "Sager Chemical Axe"
text = "1945 - 4 lb"
slug = "sager-1945"
folder = "photos/sager-1945"
ascending = true

[[section]]
title = "True Temper Red Warrior"
text = "1950's - 3½ lb"
slug = "red-warrior"
folder = "photos/red-warrior"
ascending = true

[others]
folders = [ "photos" ]
