[site]
title = "Axe Pictures"
description = "by Axe Barbie"
author = "Axe Barbie"
logo = "images/axebarbie.svg"

[[site.icons]]
icon = "images/instagram.svg"
link = "https://instagram.com/axebarbie"
label = "View Instagram profile"

[[site.icons]]
icon = "images/takemymoney.svg"
link = "https://www.ebay.com/usr/axebarbie"
label = "View eBay store"

[[site.icons]]
icon = "images/youtube.svg"
link = "https://youtube.com/@axebarbie"
label = "View YouTube channel"

[[site.nav]]
text = "Single Bits"
link = "single-bits"
label = "View single bits"

[[site.nav]]
text = "Boy's Axes"
link = "boys-axes"
label = "View boy's axes"

[[site.nav]]
text = "Hatchets"
link = "hatchets"
label = "View hatchets"

[[site.nav]]
text = "Double Bits"
link = "double-bits"
label = "View double bits"

[[site.nav]]
text = "Power Tools"
link = "power-tools"
label = "View power tools"

[[site.nav]]
text = "Catalogs"
link = "catalogs"
label = "View catalogs"

[[site.nav]]
text = "Banjo Tabs"
link = "banjo"
label = "View banjo tabs"

[image]
thumbnailWidth = 640
originalWidth = 0
compressQuality = 100

[layout]
minColumn = 3
maxColumn = 4
minWidth = 200

[others]
folders = [ "css", "images", "photos" ]

[[section]]
title = "Engineered for Axe Women Custom WA165 Work Axe"
text = "2024 - 4½ lb"
slug = "axe-barbie"
folder = "photos/axe-barbie"
ascending = true
